export const THEME_PRESETS = [
  {
    id: 'pink_classic',
    name: 'الوردي الملكي (بيت الورد الكلاسيكي 🌸)',
    badge: '🌸 كلاسيكي بيت الورد',
    desc: 'التصميم الأساسي الأنيق بتدرجات الورد الطبيعي والبنفسجي الملكي الفاخر',
    headerGradient: 'from-[#420527] via-[#2D0A4E] to-[#540D46]',
    primaryColor: '#db2777',
    primaryGradient: 'from-pink-600 via-rose-600 to-purple-600',
    secondaryGradient: 'from-pink-500 to-purple-600',
    bgClass: 'from-pink-50 via-purple-50 to-rose-50',
    headerBorder: 'border-pink-500/30',
    activeTabBg: 'from-pink-600 to-purple-600',
    buttonColor: 'bg-gradient-to-r from-pink-600 to-purple-600',
    textColor: 'text-pink-600',
    borderColor: 'border-pink-200',
    cardBg: 'bg-white',
    dark: false,
    previewColors: ['#420527', '#db2777', '#fdf2f8', '#9333ea']
  },
  {
    id: 'cute_kawaii',
    name: 'الطفولي الكيوت البلوري (عالم الباستيل والفقاعات 🫧🎀)',
    badge: '🫧 كيوت بلوري وفقاعات',
    desc: 'مظهر طفولي ساحر بألوان الباستيل البلورية (وردي كاندي، سكايبلو سماوي، لافندر ناعم) مع فقاعات كرستالية براقة تضفي بهجة ولطافة فائقة',
    headerGradient: 'from-[#FF7EB3] via-[#C084FC] to-[#60A5FA]',
    primaryColor: '#ec4899',
    primaryGradient: 'from-pink-400 via-purple-400 to-sky-400',
    secondaryGradient: 'from-pink-300 via-purple-300 to-sky-300',
    bgClass: 'from-pink-100/90 via-purple-100/80 to-sky-100/90 text-slate-800',
    headerBorder: 'border-pink-300/60 shadow-lg shadow-pink-200/50',
    activeTabBg: 'from-pink-400 via-purple-400 to-sky-400',
    buttonColor: 'bg-gradient-to-r from-pink-400 via-purple-400 to-sky-400',
    textColor: 'text-pink-600',
    borderColor: 'border-pink-200',
    cardBg: 'bg-white/95 backdrop-blur-md',
    dark: false,
    previewColors: ['#FF7EB3', '#C084FC', '#60A5FA', '#FDF2F8']
  },
  {
    id: 'dark_luxury',
    name: 'الأسود الليلي الملكي (Midnight Obsidian OLED 🌙🖤)',
    badge: '🌙 أوبسيديان ملكي OLED',
    desc: 'خلفيات كربونية داكنة فخمة باللون الأسود والأوبسيديان مريحة جداً للعين مع توهج بنفسجي ساحر وأطراف ملكية واضحة',
    headerGradient: 'from-[#07090E] via-[#0F172A] to-[#1E1B4B]',
    primaryColor: '#c084fc',
    primaryGradient: 'from-purple-500 via-violet-600 to-indigo-600',
    secondaryGradient: 'from-purple-400 to-pink-500',
    bgClass: 'from-[#07090E] via-[#0B0F19] to-[#111827] text-slate-100',
    headerBorder: 'border-purple-500/40 shadow-lg shadow-purple-950/60',
    activeTabBg: 'from-purple-600 to-indigo-600',
    buttonColor: 'bg-gradient-to-r from-purple-600 to-indigo-600',
    textColor: 'text-purple-300',
    borderColor: 'border-slate-800',
    cardBg: 'bg-slate-900/95 text-white',
    dark: true,
    previewColors: ['#07090E', '#1E1B4B', '#c084fc', '#0F172A']
  },
  {
    id: 'dark_gold_carbon',
    name: 'الكربون الذهبي الفاخر (Royal Dark Gold 👑🖤)',
    badge: '👑 كربون وذهب ملكي',
    desc: 'خلفيات ليلية سوداء ملكية مطعمة بالذهب الخالص والعنبر المشع لقصور الأفراح والمناسبات الفاخرة',
    headerGradient: 'from-[#0A0A0A] via-[#1C1917] to-[#292524]',
    primaryColor: '#f59e0b',
    primaryGradient: 'from-amber-500 via-yellow-600 to-orange-600',
    secondaryGradient: 'from-amber-400 to-yellow-500',
    bgClass: 'from-[#09090B] via-[#141416] to-[#1C1917] text-amber-100',
    headerBorder: 'border-amber-500/40 shadow-lg shadow-amber-950/60',
    activeTabBg: 'from-amber-500 to-yellow-600',
    buttonColor: 'bg-gradient-to-r from-amber-500 to-yellow-600',
    textColor: 'text-amber-400',
    borderColor: 'border-amber-900/40',
    cardBg: 'bg-stone-900/95 text-amber-50',
    dark: true,
    previewColors: ['#0A0A0A', '#1C1917', '#f59e0b', '#d97706']
  },
  {
    id: 'emerald_nature',
    name: 'الزمردي الطبيعي (نباتات وأزهار برية 🌿)',
    badge: '🌿 طبيعي وزراعي',
    desc: 'تدرجات الأخضر الزمردي المنعش المستوحى من أوراق الشجر والحدائق الطبيعية',
    headerGradient: 'from-[#064e3b] via-[#047857] to-[#0f766e]',
    primaryColor: '#059669',
    primaryGradient: 'from-emerald-600 via-teal-600 to-green-600',
    secondaryGradient: 'from-emerald-500 to-teal-600',
    bgClass: 'from-emerald-50 via-teal-50 to-green-50',
    headerBorder: 'border-emerald-500/30',
    activeTabBg: 'from-emerald-600 to-teal-600',
    buttonColor: 'bg-gradient-to-r from-emerald-600 to-teal-600',
    textColor: 'text-emerald-700',
    borderColor: 'border-emerald-200',
    cardBg: 'bg-white',
    dark: false,
    previewColors: ['#064e3b', '#059669', '#ecfdf5', '#0d9488']
  },
  {
    id: 'imperial_gold',
    name: 'الذهبي الإمبراطوري (هدايا ومناسبات فاخرة 👑)',
    badge: '👑 ذهبي وعنبر فاخر',
    desc: 'ألوان الذهب الخالص والعنبر الدافئ لتنسيق حفلات الأعراس والقصور الملكية',
    headerGradient: 'from-[#78350f] via-[#92400e] to-[#b45309]',
    primaryColor: '#d97706',
    primaryGradient: 'from-amber-600 via-yellow-600 to-orange-600',
    secondaryGradient: 'from-amber-500 to-orange-600',
    bgClass: 'from-amber-50 via-orange-50 to-yellow-50',
    headerBorder: 'border-amber-500/30',
    activeTabBg: 'from-amber-600 to-orange-600',
    buttonColor: 'bg-gradient-to-r from-amber-600 to-orange-600',
    textColor: 'text-amber-700',
    borderColor: 'border-amber-200',
    cardBg: 'bg-white',
    dark: false,
    previewColors: ['#78350f', '#d97706', '#fffbeb', '#b45309']
  },
  {
    id: 'ocean_sapphire',
    name: 'الياقوت الأزرق العصري (Sapphire Tech 🌊)',
    badge: '🌊 تقني وسريع',
    desc: 'الأزرق الملكي والسيان العصري لواجهة نقاط بيع سريعة وواضحة جداً',
    headerGradient: 'from-[#1e1b4b] via-[#1e3a8a] to-[#2563eb]',
    primaryColor: '#2563eb',
    primaryGradient: 'from-blue-600 via-indigo-600 to-cyan-600',
    secondaryGradient: 'from-blue-500 to-cyan-600',
    bgClass: 'from-blue-50 via-sky-50 to-indigo-50',
    headerBorder: 'border-blue-500/30',
    activeTabBg: 'from-blue-600 to-cyan-600',
    buttonColor: 'bg-gradient-to-r from-blue-600 to-cyan-600',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-200',
    cardBg: 'bg-white',
    dark: false,
    previewColors: ['#1e1b4b', '#2563eb', '#eff6ff', '#0284c7']
  },
  {
    id: 'lavender_dream',
    name: 'اللافندر الملكي (خزامى وبنفسج 💜)',
    badge: '💜 خزامى ملكي',
    desc: 'تدرجات زهور اللافندر الهادئة والبنفسج العطري لمظهر أنيق ومميز',
    headerGradient: 'from-[#4c1d95] via-[#5b21b6] to-[#7c3aed]',
    primaryColor: '#9333ea',
    primaryGradient: 'from-purple-600 via-fuchsia-600 to-violet-600',
    secondaryGradient: 'from-purple-500 to-fuchsia-600',
    bgClass: 'from-purple-50 via-fuchsia-50 to-violet-50',
    headerBorder: 'border-purple-500/30',
    activeTabBg: 'from-purple-600 to-fuchsia-600',
    buttonColor: 'bg-gradient-to-r from-purple-600 to-fuchsia-600',
    textColor: 'text-purple-700',
    borderColor: 'border-purple-200',
    cardBg: 'bg-white',
    dark: false,
    previewColors: ['#4c1d95', '#9333ea', '#faf5ff', '#c026d3']
  }
];

export const ARABIC_FONTS = [
  { id: 'Cairo', name: 'خط القاهرة (Cairo)', desc: 'الخط الافتراضي المعتمد، فائق الوضوح للشاشات اللمسية والكاشير السريع' },
  { id: 'Tajawal', name: 'خط تجوال (Tajawal)', desc: 'خط عصري ناعم وجذاب للمحلات الراقية والهدايا' },
  { id: 'Almarai', name: 'خط المراعي (Almarai)', desc: 'خط رسمي هندسي متناسق للفواتير والتقارير المالية' },
  { id: 'Alexandria', name: 'خط الإسكندرية (Alexandria)', desc: 'خط حديث يجمع بين الأناقة والوضوح التام' }
];

export const FONT_SIZES = [
  { id: 'normal', name: 'قياسي مريح (100%)', scale: '1' },
  { id: 'large', name: 'كبير للشاشات اللمسية (110%)', scale: '1.1' },
  { id: 'extra', name: 'فائق الوضوح (120%)', scale: '1.2' }
];
